version: "3"
services:
  redis:
    image: "redis:alpine"
    container_name: iot_redis
    ports:
      - '6379:6379'

  mysql:
    image: mysql:8.0.22
    container_name: iot_db
    volumes:
      - ./mysql/sql/:/usr/share/sql/
      - ./mysql/config/my.cnf:/etc/my.cnf
      - ./mysql/data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'iotdata'
      MYSQL_ROOT_PASSWORD: '123456'
      TZ: Asia/shanghai

  clickhouse-server:
    # image：指定镜像，可以为镜像名称或镜像id，如果本地没有该镜像，compose会尝试pull该镜像
    image: yandex/clickhouse-server
    # container_name：指定容器名称，默认为 项目名称_服务名称_序号 的格式
    container_name: iot_clickhouse-server
    # networks配置该容器连接的网络，指定到文件末尾定义的networks
    # ports：暴露端口信息，格式为 宿主机端口:容器端口；仅指定容器端口时，宿主机会随机选择端口，类似于docker run -p
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9004:9004"
    volumes:
      - ./data:/var/lib/clickhouse

  elasticsearch:
    image: elasticsearch:7.12.1
    container_name: iot_elasticsearch
    user: root
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms8G -Xmx8G"
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
#    试图挂载 但挂不上去
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "10"

#  kibana:
#    container_name: iot_kibana
#    image: docker.elastic.co/kibana/kibana:7.16.2
#    environment:
#      - elasticsearch.url=http://127.0.0.1:9200
#      - CONTAINER_TIMEZONE=Asia/Shanghai
#    ports:
#      - '5601:5601'
#
#  zookeeper:
#    image: 'bitnami/zookeeper:latest'
#    container_name: iot_zookeeper
#    ports:
#      - '2181:2181'
#    environment:
#      - CONTAINER_TIMEZONE=Asia/Shanghai
#      - ALLOW_ANONYMOUS_LOGIN=yes
#
#  kafka:
#    image: 'bitnami/kafka:latest'
#    container_name: iot_kafka
#    ports:
#      - '9092:9092'
#    environment:
#      - CONTAINER_TIMEZONE=Asia/Shanghai
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    depends_on:
#      - zookeeper