server:
  port: 8080
elasticsearch:
  rest:
    hosts: 127.0.0.1:9200
spring:
  elasticsearch:
    rest:
      uris: http://127.0.0.1:9200
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 1000
    database: 0
    lettuce:
      pool:
        min-idle: 1
        max-idle: 10
        max-active: 10
        max-wait: 1000
      shutdown-timeout: 1000
  clickhouse:
    driver-class-name: com.github.housepower.jdbc.ClickHouseDriver
    url: jdbc:clickhouse://localhost
    port: 19000
    database: tutorial
    username: default
    password:
  jpa:
    clickhouse:
      driver-class-name: com.github.housepower.jdbc.ClickHouseDriver
      url: jdbc:clickhouse://localhost
      port: 19000
      database: tutorial
      username: default
      password:
      table-update: true
      hikari:
        # 连接池的最大连接数
        maximumPoolSize: 60
        # 空闲超时
        idleTimeout: 1000000
        # 连接超时时间
        connectionTimeout: 5000

  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      acks: 0