server:
  port: 8080
elasticsearch:
  rest:
    hosts: 127.0.0.1:9200
spring:
  elasticsearch:
    rest:
      uris: http://127.0.0.1:9200

  redis:
    host: 127.0.0.1
    port: 16379
    password:
    timeout: 5000
    database: 0
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10
        max-active: 10
        max-wait: 1000
      shutdown-timeout: 1000
  clickhouse:
    driver-class-name: com.github.housepower.jdbc.ClickHouseDriver
    url: jdbc:clickhouse://localhost
    port: 19000
    database: tutorial
    username: default
    password:
  jpa:
    clickhouse:
      driver-class-name: com.github.housepower.jdbc.ClickHouseDriver
      url: jdbc:clickhouse://localhost
      port: 19000
      database: tutorial
      username: default
      password:
      table-update: true
      hikari:
        # 连接池的最大连接数
        maximumPoolSize: 60
        # 空闲超时
        idleTimeout: 1000000
        # 连接超时时间
        connectionTimeout: 5000
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/iotdata?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      acks: 0
google:
  s2:
    level: 20
cache:
  redis:
    expires: 3600
  caffeine:
    expires: 3600
    maximumSize: 10000
job:
  executor:
    corePoolSize: 6
    maxPoolSize: 12
    keepAliveSeconds: 6000
    queueCapacity: 1000
    workerExecutorPrefix: ASaltyFish-WorkerExecutor-
    bossExecutorPrefix: ASaltyFish-BossExecutor-
  timeWheel:
    tick: 1000
    size: 100
wal:
  enabled: true
  flushIntervalMs: 1000
  flushSize: 200
