server:
  port: 8080
elasticsearch:
  rest:
    hosts: 127.0.0.1:9200
spring:
  elasticsearch:
    rest:
      uris: http://127.0.0.1:9200
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 1000
    database: 0
    lettuce:
      pool:
        min-idle: 1
        max-idle: 10
        max-active: 10
        max-wait: 1000
      shutdown-timeout: 1000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iotdata?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  clickhouse:
    driver-class-name: com.github.housepower.jdbc.ClickHouseDriver
    url: jdbc:clickhouse://localhost
    port: 19000
    database: tutorial
    username: default
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      acks: 0